### ISSUE TITLE
Plan to release vignette or notebook to run analysis?

### ISSUE THREAD

**Issue by giovp** [solevillar/scGeneFit#1]
Hi,

thank you very much for releasing the code, read the preprint today, really smart alternative to marker selection via differential analysis.

Unfortunately, I am not familiar with matlab, would it be possible to have a sketch of a step-by-step guide to run the analysis? I understand the main function is at source/scGeneFit.m, would it be possible to use it as is?

Thanks in advance,

Giovanni

**Comment by solevillar** [comment]
Hi Giovanni,
Basically any system that has a good linear program solver would work. What
LP solver do you use? I think python should have one but I think it works
in a much smaller scale (since matlab's optimization tools seem to be more
efficient than python's). I could write a jupyter notebook that could work
for smaller datasets. What is the size of the problems you are looking at?
Best,
Soledad

**Comment by giovp** [comment]
Hi Soledad,

thanks for the prompt reply. Dataset is ~10k cells and ~5k features. A jupyter notebook would be great! Thank you! 

Best,
Giovanni

**Comment by solevillar** [comment]
Hi Giovanni,
Sorry for the delay, I just uploaded a simplified version of the code in python, with a jupyter notebook with examples of how to use it. It's here https://github.com/solevillar/scGeneFit-python

10k cells and 5k features seems too large of a problem to use the LP directly but it may work if you have enough memory. Otherwise try reducing the dataset to fewer features (around 1k?). How many markers do you need?

**Comment by giovp** [comment]
Will have a look at the repo, thanks a lot!
Will try to reduce the features, thanks for the suggestions.
